# Base on alpine OS 
FROM alpine:latest 

# 
WORKDIR /user/local/bin 

# Make simple hello script
RUN echo "echo \"Hello Alpine\"" > ./hello.sh 
RUN chmod u+x *.sh

# Run the hello script 
ENTRYPOINT ["sh", "./hello.sh"]
