version: "3.9"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 57017:27017
    
  web:
    build: .
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@db:27017/todo_db?authSource=admin
    ports:
      - 30000:3000
    volumes:
      - ./app:/usr/src/app



